export const WEATHER_FETCH_LOCATION = 'WEATHER_FETCH_LOCATION';
export type WEATHER_FETCH_LOCATION = typeof WEATHER_FETCH_LOCATION;
export const WEATHER_REQUESTED = 'WEATHER_REQUESTED';
export type WEATHER_REQUESTED = typeof WEATHER_REQUESTED;
export const WEATHER_REQUESTED_SUCCEEDED = 'WEATHER_REQUESTED_SUCCEEDED';
export type WEATHER_REQUESTED_SUCCEEDED = typeof WEATHER_REQUESTED_SUCCEEDED;
